### PR TITLE
Created a script to compute factoids for COD:WW2 tournaments

### PR DESCRIPTION
**Pull request by lot9s**
To create this script, I used [`compute-factoids.py`](https://github.com/Activision/cwl-data/blob/master/tools/compute-factoids.py) as a base and made the following changes:
* removed COD:IW-specific code (i.e. uplink stats)
* added COD:WW2-specific code (i.e. Capture the Flag stats)
* added ability to specify path to any COD:WW2 data set on command line

### CODE REVIEW

**Comment by saturnboy** [comment]
@lot9s thanks for this...but let's not make a separate file, instead let's merge these two factoid helpers together (ex: include `--title` flag for `iw` or `ww2`, a block of total stats to compute per title, a block of record stats to compute per title, etc)

**Comment by lot9s** [comment]
@saturnboy Okay! Will do. I'll submit a different pull request at a later time after making this happen.

Before closing this pull request, could you please clarify what you meant by, "...a block of total stats to compute per title, a block of record stats to compute per title, etc"? Are you suggesting that the script should accept a list of stats to compute from the command line?

**Comment by saturnboy** [comment]
@lot9s I was thinking something like this:

```py
TITLES = {
    'iw': {'modes': ['hp', 'snd', 'upl']},
    'ww2': {'modes': ['hp', 'snd', 'ctf']}
}
TOTALS = {
    'base': ['kills', 'deaths', 'assists', 'hits', 'shots'],
    'hp': ['hill time (s)'],
    'snd': ['bomb plants', 'bomb defuses'],
    'upl': ['uplink dunks', 'uplink throws', 'uplink points'],
    'ctf': ['ctf captures', 'ctf returns', 'ctf pickups', 'ctf defends', 'ctf kill carriers', 'ctf flag carry time (s)']
}

def find_totals(rows, title):
    """Compute stat totals by summing over the entire tournament."""
    totals = {k:0 for k in [k for l in [TOTALS[i] for i in ['base'] + TITLES[title]['modes']] for k in l]}
    for row in rows:
        for k in totals:
            totals[k] += int(row[k])

    return totals
```

Or maybe this is simpler and better:

```py
TOTALS = {
    'iw':  ['kills', 'deaths', 'assists', 'hits', 'shots', 'hill time (s)', 'bomb plants', 'bomb defuses', 'uplink dunks', 'uplink throws', 'uplink points'],
    'ww2': ['kills', 'deaths', 'assists', 'hits', 'shots', 'hill time (s)', 'bomb plants', 'bomb defuses', 'ctf captures', 'ctf returns', 'ctf pickups', 'ctf defends', 'ctf kill carriers', 'ctf flag carry time (s)']
}

def find_totals(rows, title):
    """Compute stat totals by summing over the entire tournament."""
    totals = {k:0 for k in TOTALS[title]}
    for row in rows:
        for k in totals:
            totals[k] += int(row[k])

    return totals
```

Also, no need to close, the theme of this branch is "improved factoids for ww2", so just keep going..

**Comment by lot9s** [comment]
@saturnboy I took some time this afternoon to make the desired changes to the factoid script. Please take a look to make sure that it all checks out.

**Pull request merged**
